# 예외
자바 개발자가 가장 신경 쓰기 귀찮아하는 것 중의 하나가 바로 예외처리다. 그래서 예외와 관련된 코드는 자주 엉망이 되거나 무성의하게 만들어지기 쉽다. 때론 잘못된 예외처리 코드 때문에 찾기 힘든 버그를 낳을 수도 있고, 생각지 않았던 예외상황이 발생했을 때 상상 이상으로 난처해질 수도 있다.

이번장에서는 JdbcTemplate을 대표로 하는 스프링의 데이터 액세스 기능에 담겨 있는 예외처리와 관련된 접근 방법에 대해 알아보자.

## 사라진 SQLException
3장에서 JdbcContext로 만들었던 코드를 스프링의 JdbcTempalte을 적용하도록 바꾸면서 얼렁뚱땅 넘어간 부분이 있다. 바꾸기 전후의 deleteAll() 메소드를 비교해보자.

~~~java
// 전
public void deleteAll() throws SQLException {
  this.jdbcContext.executeSql("delete from users");
}

// 후
public void deleteAll() {
  this.jdbcTemplate.update("delete from users");
}
~~~
바꾸기 전에 있던 throws SQLException 선언이 바꾼 뒤로는 사라졌다. SQLException 은 JDBC API 의 메소드들이 던지는 것이므로 당연히 있어야한다. 비록 로그를 남기기 위해 catch를 했다고 해도 다시 JDBC 템플릿 메소드밖으로 던져서 예외상황이 발생했다는 사실을 알려야 한다. 그런데 JdbcTemplate을 적용한 코드에서는 사라졌다. SQLException은 어디로 간 것일까?

### 초난감 예외처리
JdbcTemplate이 어떤 짓을 했길래 SQLException이 사라졌는지 알아보기 위해 먼저 개발자들의 코드에서 종종 발견되는 초난감 예외처리의 대표코드를 살펴보자.

#### 에외 블랙홀
~~~ java
// 초난감 예외처리 코드
try {
  ...
} catch(SQLException e) { }
~~~
여기서 catch(SQLException e) {} 는 예외 발생을 무시해버리고 정상적인 상황인 것처럼 다음 라인으로 넘어가겠다는 의도가 있는 게 아니라면 연습 중에도 절대 만들어서는 안 되는 코드다.

JDBC API를 썼더니 IDE가 빨간 줄을 그어주며 '처리되지 않은 예외가 있다'고 에러를 표시해 준다. 이를 보고 자바 기초로 배운 try/catch 블록을 둘러싸주는 것으로 해결한다. 물론 컴파일 에러 메세지도 없어지고 별 문제 없이 동작한다.

이런 식의 코드가 자바 서적의 예제나 강의 자료에도 심심치 않게 등장하고, 유명 오픈소스 제품의 코드나 실전 프로젝트의 작성된 코드에서도 나타나는 것을 보면 초보자의 실수라고만 볼 수는 없다. 이런 잘못된 습관이 계속 남아 있는 게 문제의 원인일 것이다.

예외가 발생하면 그것을 catch 블록을 써서 잡아내는 것까지는 좋은데 아무것도 하지 않고 별문제 없는 것처럼 넘어가 버리는 건 정말 위험하다. 왜냐하면 프로그램 실행 중에 어디선가 오류가 있어서 예외가 발생했는데 그것을 무시하고 계속 진행해버리기 때문이다.

결국 발생한 예외로 인해 어떤 기능이 비정상적으로 동작하거나, 메모리나 리소스가 소진되거나, 예상치 못한 다른 문제를 일으킬 것이다. 최종적으로는 오작동을 하거나 시스템 오류가 나서 개발자가 알아차렸을 때는 이미 조치를 취하기에 늦다. 더 큰 문제는 그 시스템 오류나 이상한 결과의 원인이 무엇인지 찾아내기가 매우 힘들다는 점이다.

어떤 경우에도 위와 같이 빈 catch 블록을 사용하면 안된다.

아래의 코드도 마찬가지다
~~~java
} catch(SQLException e) {
  System.out.println(e);
}
~~~

~~~java
} catch(SQLException e) {
  e.printStackTrace();
}
~~~

예외가 발생하면 화면에 출력해주는데 어떤 점이 문제일까? 다른 로그나 메세지에 금방 묻혀버리면 놓치기 쉽상이며, 운영서버에 올라가면 콘솔로그를 누군가가 계속 모니터링하지 않는 한 심각한 폭탄으로 남아 있을 것이다. catch 블록을 이용해 화면에 메세지를 출력한 것은 예외 처리한 게 아니다.

예외를 처리할 때 반드시 지켜야 할 핵심 원칙은 한 가지다. 모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 개발자에게 분명하게 통보돼야 한다.

SQLException이 발생하는 이유는 SQL에 문법 에러가 있거나 DB에서 처리할 수 없을 정도로 데이터 액세스 로직에 심각한 버그가 있거나, 서버가 죽거나 네트워크가 끊기는 등의 심각한 상황이 벌어졌기 때문이다. 그런데 그냥 예외를 무시하고 정상적으로 동작하고 있는 것처럼 모른 척 다음 코드로 실행을 이어간다는 건 말이 되지 않는다. 콘솔이나 로그에 예외 메시지를 출력하는 건 아무런 도움이 되지 않는다.

차라리 아래와 같은 코드가 더 낫다
~~~java
//그나마 나은 예외처리
} catch(SQLException e) {
  e.printStackTrace();
  System.exit(1);
}
~~~

물론 실전에서 이렇게 만들라는 것은 아니다. 예외를 무시하거나 잡아먹어 버리는 코드는 만들지 말라는 의미다. 굳이 예외를 잡아서 뭔가 조치를 취할 방법이 없다면 잡지 말아야 한다. 메소드에 throws SQLException을 선언해서 메소드 밖으로 던지고 자신을 호출한 코드에 예외처리 책임을 전가해버려라.

#### 무의미하고 무책임한 throws
catch 블록으로 예외를 잡아봐야 해결할 방법도 없고 JDK API나 라이브러리가 던지는 각종 이름도 긴 예외들을 처리하는 코드를 매번 throws로 선언하기도 귀찮아지기 시작하면, 아래와 같이 메소드 선언에 throws EXception을 기계적으로 붙이는 개발자도 있다.

~~~java
// 초난감 예외처리4
public void methos1() throws EXception {
  method2();
  ...
}

public void method2() throws Exception {
  method3();
  ...
}

public void mehtod3() throws Exception {
  ...
}
~~~

API 등에서 발생하는 예외를 일일이 catch하기 귀찮고, 별 필요도 없으며 매번 정확하게 예외 이름을 적어서 선언하기도 귀찮으니 아예 throws Exception이라는, 모든 예외를 무조건 던저버리는 선언을 모든 메소드에 기계적으로 넣는 것이다. 예외를 흔적도 없이 먹어치우는 예외 블랙홀보다는 조금 낫긴 하지만 이런 무책임한 throws 선언도 심각한 문제점이 있다.

자신이 사용하려고 하는 메소드에 throws Exception이 선언되어 있다고 생각해보자, 그런 메소드 선언에서는 의미 있는 정보를 얻을 수 없다. 결국 이런 메소드를 사용하는 메소드에서도 역시 throws Exception을 따라서 붙이는 수밖에 없다. 결과적으로 적절한 처리를 통해 복구될 수 있는 예외상황도 제대로 다를 수 있는 기회를 박탈당한다.

예외를 무시해버리는 첫 번째 문제보다는 낫다고 하지만 이런 코드도 매우 안좋은 예외처리 방법이다.

이 두 가지 나쁜 습관은 어떤 경우에도 용납하지 않아야 한다.

### 예외의 종류와 특징
그렇다면 예외를 어떻게 다뤄야 할까? 예외처리에 관해서는 자바 개발자들 사이에서도 오랫동안 많은 논쟁이 있었다. 가장 큰 이슈는 체크 예외(checked exception)라고 불리는 명시적인 처리가 필요한 예외를 사용하고 다루는 방법이다.

자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있다.

- Error
첫번째는 java.lang.Error 클래스의 서브클래스들이다. 에러는 시스템에 뭔가 비정상적인 상황이 발생했을 경우에 사용된다. 그래서 주로 자바 VM에서 발생시키는 것이고 애플리케이션 코드에서 잡으려고 하면 안 된다. OutOfMemoryError나 ThreadDeath 같은 에러는 CATCH 블록으로 잡아봤자 아무런 대응 방법이 없기 때문이다.
따라서 시스템 레벨에서 특별한 작업을 하는 게 아니라면 애플리케이션에서는 이런 에러에 대한 처리는 신경 쓰지 않아도 된다.

- Exception과 체크 예외
java.lang.Exception 클래스와 그 서브클래스로 정의되는 예외들은 에러와 달리 개발자들이 만든 애플리케이션 코드의 작업 중에 예외상황이 발생했을 경우에 사용된다.
Exception 클래스는 다시 체크 예외와 언체크 예외(unchecked exception)로 구분된다. 전자는 Exception 클래스의 서브클래스이면서 RuntimeException 클래스를 상속하지 않은 것들이고, 후자는 RunTimeException을 상속한 클래스들을 말한다.
RunTimeException은  Exception의 서브클래슫이므로 Exception의 일종이긴 하지만 자바는 이 RuntimeException과 그 서브클래스는 특별하게 다룬다. 아래는 Exception 클래스의 서브클래스를 체크 예외와 언체크 예외로 구분한 것이다.
~~~

~~~
일적으로 예외는 Exception 클래스의 서브클래스 중에서 RuntimeException을 상속하지 않은 것만을 말하는 체크 예외라고 생각해도 된다. 체크 예외가 발생할 수 있는 메소드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야 한다. 사용할 메소드가 체크 예외를 던진다면 이를 catch 문으로 잡든지, 아니면 다시 throws를 정의해서 메소드 밖으로 던져야 한다. 그렇지 않으면 컴파일 에러가 발생한다.

- RuntimeException과 언체크/런타임 예외
java.lang.RuntimeException 클래스를 상속한 예외들은 명시적인 예외처리를 강제하지 않기 때문에 언체크 예외라고 불린다. 또는 대표 클래스 이름을 따서 럼타임 예외라고도 한다. 에러와 마찬가지로 이 런타임 예외는 catch 문으로 잡거나 throws로 선언하지 않아도 된다. 물론 명시적으로 잡거나 선언해도 상관은 없다.
런타임 예외는 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들이다. 대표적으로 오브젝트를 할당하지 않은 레퍼런스 변수를 사용하려고 시도했을 때 발생하는 NullPointerException이나, 허용되지 않는 값을 사용해서 메소드를 호출할 때 발생하는 IllegalArgumentException 등이 있다. 이런 예외는 코드에서 미리 조건을 체크하도록 주의 깊게 만든다면 피할 수 있다.

피할 수 있지만 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 마든 것이 런타임 예외다. 따라서 런타임 예외는 예상하지 못했던 예외상황에서 발생하는 게 아니기 때문에 굳이 catch나 throws를 사용하지 않아도 되도록 만든 것이다.

그런데 자바 언어를 설계하고 JDK를 개발한 사람들의 이런 설계의도는 현실과 잘 맞지 않았고 비난의 대상이 되기도 했다. 특히 체크 예외의 불필요성을 주장하는 사람들이 늘어갔다. 체크 예외가 예외처리를 강제하는 것 때문에 예외 블랙홀이나 무책임한 throws 같은 코드가 남발됐다. 최근에 새로 등장하는 자바 표준 스펙의 API들은 예상 가능한 예외상황을 다루는 예외를 체크 예외로 만들지 않는 경향이 있기도 하다.

### 예외처리 방법
일반적인 예외처리 방법을 살펴보고나서 효과적인 예외처리 전략을 생각해보자.

#### 예외 복구
첫 번째 처리 방법은 예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것이다.

예를 들어 사용자가 요청한 파일을 읽으려고 시도했는데 어떤 문제로 읽히지 않아 IOException이 발생했다고 생각해보자. 이때는 사용자에게 상황을 알려주고 다른 파일을 이용하도록 안내해서 예외상황을 해결할 수 있다. 예외로 인해 기본 작업 흐름이 불가능하면 다른 작업 흐름으로 자연스럽게 유도해주는 것이다.

이런 경우 예외상황은 다시 정상으로 돌아오고 예외를 복구했다고 볼 수 있다. 단, IOException 에러 메세지가 사용자에게 그냥 던져지는 것은 예외 복구라고 볼 수 없다. 예외가 처리됐으면 비록 기능적으로는 사용자에게 예외상황으로 비쳐도 애플리케이션에서는 정상적으로 설계된 흐름을 따라 진행돼야 한다.

네트워크가 불안해서 가끔 서버에 접속이 잘 안 되는 열악한 환경에 있는 시스템이라면 원격 DB 서버에 접속하다 실패해서 SQLException이 발생하는 경우에 재시도를 해볼 수 있다. 네트워크 접속이 원할하지 않아서 예외가 발생했다면 일정 시간 대기했다가 다시 접속을 시도해보는 방법을 사용해서 예외상황으로부터 복구를 시도할 수 있다. 물론 정해진 횟수만큼 재시도해서 실패했다면 예외 복구는 포기해야 한다.

예외처리 코드를 강제하는 체크 예외들은 이렇게 예외를 어떤 식으로든 복구할 가능성이 있는 경우에 사용한다. API를 사용하는 개발자로 하여금 예외상황이 발생할 수 있음을 인식하도록 도와주고 이에 대한 적절한 처리를 시도해보도록 요구하는 것이다.

아래는 통제 불가능한 외부 요인으로 인해 예외가 발생하면 MAX_RETRY만큼 재시도를 하는 간단한 예이다. 사전에 미리 성공 여부를 확인할 수 없고, 재시도가 의미있는 경우라면 이렇게 최대 횟수만큼 반복적으로 시도함으로써 예외상황에서 복구되게 할 수 있다.

~~~java
// 재시도를 통해 예외를 복구하는 코드
int maxretry = MAX_RETRY;
while(maxretry-- > 0) {
  try {
    ... // 예외가 발생할 가능성이 있는 시도
    return; // 작업 성공
  }
  catch(SomeException e) {
    // 로그 출력, 정해진 시간만큼 대기
  }
  finally {
    // 리소스 반납. 정리 작업
  }
}

throw new RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외 발생
~~~

#### 예외처리 회피
두 번째 방법은 예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버리는 것이다. throws 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch 문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는 rethrow것이다.

예외를 자신이 처리하지 않고 회피하는 방법이다. 빈 catch 블록으로 잡아서 예외가 발생하지 않은 것처럼 만드는 경우는, 드물지만 특별한 의도를 가지고 예외를 복구했거나 아무 개념이 없어서 그런 것이지 회피한 것은 아니다. 예외처리를 회피하려면 반드시 다른 오브젝트나 메소드가 예외를 대신 처리할 수 있도록 아래처럼 던져줘야 한다.

~~~java
// 예외처리 회피1
public void sadd() throws SQLException {
  ///JDBC API
}
~~~

~~~java
// 예외처리 회피2
public void add() throws SQLException {
  try {
    // JDBC API
  }
  catch(SQLException e) {
    // 로그 출력
    throw e;
  }
}
~~~
JdbcContext나 JdbcTemplate이 사용하는 콜백 오브젝트는 메소드 선언을 보면 알겠지만 ResultSet이나 PreparedStatement등을 이용해서 작업하다 발생하는 SQLException을 자신이 처리하지 않고 템플릿으로 던져버린다. 콜백 오브젝트의 메소드는 모두 thorws SQLException이 붙어 있다. SQLException을 처리하는 일은 콜백 오브젝트의 역할이 아니라고 보기 때문이다. 콜백 오브젝트의 메소드는 SQLException에 대한 예외를 회피하고 템플릿 레벨에서 처리하도록 던져준다.

하지만 콜백과 템플릿처럼 긴밀하게 역할을 분담하고 있는 관계가 아니라면 자신의 코드에서 발생하는 예외를 그냥 던져버리는 건 무책임한 책임회피일 수 있다. 만약 DAO가 SQLException을 생각 없이 던져버리면 어떻게 될까? DAO를 사용하는 서비스 계층이나 웹 컨트롤러에서 과연 SQLException을 제대로 처리할 수 있ㅇ르까? 아마도 이런 경우라면 DAO에서 던진 SLQLException을 서비스 계층 메소드가 다시 던지고, 컨트롤러도 다시 던지도록 선언해서 예외는 그냥 서버로 전달되고 말 것이다. 아마도 throws SQLException과 같이 구체적인 예외를 던지도록 선언하기가 귀찮아서 모든 예외를 생각없이 던져버리게 하는 throws Exception을 사용할 가능성이 높다.

예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다. 콜백/템플릿처럼 긴밀한 관계에 있는 다른 오브젝트에게 예외처리 책임을 분명히 지게 하거나, 자신을 사용하는 쪽에서 예외를 다루는 게 최선의 qkdqjqdlfksms 분명한 확신이 있어야한다.

#### 예외 전환
마지막으로 예외를 처리하는 방법은 예외 전환(exception translation)을 하는 것이다. 예외 회피와 비슷하게 예외를 복구해서 정상적인 상태로는 만들 수 없기 때문에 예외를 메소드 밖으로 던지는 것이다. 하지만 예외 회피와 달리, 발생한 예외를 그대로 넘기는 게 아니라 적절한 예외로 전환해서 던진다는 특징이 있다.

예외 전환은 보통 두 가지 목적으로 사용한다.
첫째는 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우에, 의미를 분명하게 핼줄 수 있는 예외로 바꿔주기 위해서다. API가 발생하는 기술적인 로우레벨을 상황에 적합한 의미를 가진 예외로 변경하는 것이다.

예를 들어 새로운 사용자를 등록하려고 시도했을 때 아이디가 같은 사용자가 있어서 DB 에러가 발생하면 JDBC API는 SQLException을 발생시킨다. 이 경우 DAO 메소드가 SQLException을 그대로 밖으로 던져버리면, DAO를 이용해 사용자를 추가하려고 한 서비스 계층 등에서는 왜 SQLException이 발생헀는지 쉽게 알 방법이 없다. 로그인 아이디 중복 같은 경우는 충분히 예상 가능하고 복구 간으한 예외상황이다. 이럴 땐 DAO에서 SQLException의 정보를 해석해서 DuplicationUserIdException 같은 예외로 바꿔서 던져주는 게 좋다.

의미가 분명한 예외가 던져지면 서비스 계층 오브젝트에는 적절한 복구 작업을 시도할 수가 있다. 서비스 계층 오브젝트에서 SQLException의 원인을 해석해서 대응하는 것도 불가능하지는 않지만, 특정 기술의 정보를 해석하는 코드를 비즈니스 로직을 담은 서비스 계층에 두는 건 매우 어색하다. 따라서 DAO 메소드에서 기술에 독립적이며 의미가 분명한 예외로 전환해서 던져줄 필요가 있다.

아래는 사용자 정보를 등록하려고 시도해보고, 만약 중복된 아이디 값 때문에 에러가 나는 경우에는 이를 확인해서 좀 더 의미 있는 DuplicateKeyException으로 전환해주는 DAO메소드의 예다.

~~~java
// 예외 전환 기능을 가진 DAO 메소드
public void add(User user) throws DuplicateUserIdException, SQLException {
  try {
    // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
    // 그런 기능을 가진 다른 SQLException을 던지는 메소드를 호출하는 코드
  }
  catch(SQLException e) {
    //ErrorCode가 MySQL의 Duplicate Entry(1062)이면 예외 전환
    if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
      throw DuplicateUserIdException();
    else
      throw e;
  }
}
~~~
보통 전환하는 예외에 원래 발생한 예외를 담아서 중첩 예외(nested exception)로 만드는 것이 좋다. 중첩 예외는 getCause() 메소드를 이용해서 청므 발생한 예외가 무엇인지 확인할 수 있다. 중첩 예외는 아래처럼 새로운 예외를 만들면서 생성자난 initCause() 메소드로 근본 원인이 되는 예외를 넣어주면 된다.

~~~java
// 중첩 예외1
catch(SQLException e) {
  ...
  throw DuplicateUserIdException(e);
}
~~~
~~~java
// 중첩 예외2
catch(SQLException e) {
  ...
  throw DuplicateUserIdException().initCause(e);
}
~~~
두 번째 전환 방법은 예외를 처리하고 쉽고 단순하게 만들기 위해 포장(wrap)하는 것이다. 중첩 예외를 이용해 새로운 예외를 만들고 원인이 되는 예외를 내부에 담아서 던지는 방식은 같다. 하지만 의미를 명확하게 하려고 다른 예외로 전환하는 것이 아니다. 주로 예외처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우에 사용한다.

대표적으로 EJBException을 들 수 있다. EJB 컴포넌트 코드에서 발생하는 대부분의 체크 예외는 비즈니스 로직으로 볼 때 의미 있는 예외이거나 복구 가능한 예외가 아니다. 이런 경우에는 런타임 예외인 EJBException으로 포장해서 던지는 편이 낫다. 아래 예처럼 말이다.

~~~java
// 예외 포장
try {
  OrderName orderName = EJBHomeFactory.getInstance().getOrderHome();
  Order order = orderHome.findByPrimaryKey(Integer id);
} catch(NamingException ne) {
  throw new EJBException(ne);
} catch(SQLException se) {
  throw new EJBException(se);
} catch(RemoteException re) {
  throw new EJBException(re);
}
~~~
EJBException은 RuntimeException 클래스를 상속한 런타임 예외다. 이렇게 런타임 예외로 만들어서 전달하면 EJB는 이를 시스템 익셉션으로 인식하고 트랜잭션을 자동으로 롤백해준다. 런타임 예외이기 때문에 EJB 컴포넌트를 사용하는 다른 EJB난 클라이언트에서 일일이 예외를 잡거나 다시 던지는 수고를 할 필요가 없다. 이런 예외는 잡아도 복구할 만한 방법이 없기 때문이다.

반대로 애플리케이션 로직상에서 예외조건이 발견되거나 예외상황이 발생할 수도 있다. 이런 것은 API가 던지는 예외가 아니라 애프리케이션 코드에서 의도적으로 던지는 예외다. 이때는 체크 예외를 사용하는 것이 적절하다. 비즈니스적인 의미가 있는 예외는 이에 대한 적절한 대응이나 복구 작업이 필요하기 때문이다.

일반적으로 체크 예외를 계속 throws를 사용해 넘기는 건 무의미하다. 메소드 선언은 지저분해지고 아무런 장점이 없다. DAO에서 발생한 SQLException이 웹 컨트롤러 메소드까지 명시적으로 전달된다고 해서 무슨 소용이 있을까? 웹 컨트롤러 메소드에 throws SQLException 선언이 달려 있다면 이를 도대체 어떻게 해석해야 할까? 어차피 복구가 불가능한 예외라면 가능한 한 빨리 런타임 예외로 포장해 던지게 해서 다른 계층의 메소드를 작성할 때 불필요한 throws 선언이 들어가지 않도록 해줘야 한다.

대부분 서버환경에서는 애프릴케이션 코드에서 처리하지 않고 전달된 예외들을 일괄적으로 다룰 수 있는 기능을 제공한다. 어차피 복구하지 못할 예외라면 애플리케이션 코드에서는 런타임 예외로 포장해서 던져버리고, 예외처리 서비스 등을 이용해 자세한 로그를 남기고, 관리자에게는 메일 등을로 통보해주고, 사용자에게는 친절한 안내 메시지를 보여주는 식으로 처리하는 게 바람직하다.

### 예외처리 전략
사실 자바의 예외를 이용하는 것은 간단하다. 하지만 예외를 효과적으로 사용하고, 예외가 발생하는 코드를 깔끔하게 정리하는 데는 여러 겨자 신경 써야 할 사항이 많다. 지금까지 살펴본 예외의 종류와 처리 방법 등을 기준으로 일관된 예외처리 전략을 정리해보자.

#### 런타임 예외의 보편화
일반적으로는 체크 예외가 일반적인 예외를 다루고, 언체크 예외는 시스템 장애나 프로그램상의 오류에 사용한다고 헀다. 문제는 체크 예외는 복구할 가능성이 조금이라도 있는, 말 그대로 예외적인 상황이기 때문에 자바는 이를 처리하는 catch 블록이나 throws 선언을 강제하고 있다는 점이다. 이렇게 예외처리를 강제하는 것은 예외가 발생할 가능성이 있는 API 메소드를 사용하는 개발자의 실수를 방지하기 위한 배려라고 볼 수도 있겠지만, 실제로는 예외를 제대로 다루고 싶지 않을 만큼 짜증나게 만드는 우너인이 되기도 한다.

자바가 청므 만들어질 떄 많이 사용되던 애플릿이나 AWT, 스윙을 사용한 독립형 애플리케이션에서는 통제 불가능한 시스템 예외라고 할지라도 애플리케이션의 작업이 중단되지 않게 해주고 상황을 복구해야 했다. 예를 들어 워드의 팡리 열기 기능에서 사용자가 입력한 이름에 해당하는 파일을 찾을 수 없다고 애프리렠이션이 종료돼버리게 할 수는 없다.

하지만 자바 엔터프라이즈 서보환경은 다르다. 수많은 사용자가 동시에 요청을 보내고 각 용청이 독립적인 작업으로 취급된다. 하나의 요청을 처리하는 중에 예외가 발생하면 해당 작업만 중단시키면 그만이다. 독립현 애플리케이션과 달리 서버의 특정 계층에서 에외가 발생했을 때 작업을 일시 중지하고 사용자와 바로 커뮤니케이션함녀서 예외상황을 복구할 수 있는 방법이 없다.

차라리 애프릴케이션 차우너에서 예외상황을 미리 파악하고, 예외가 발생하지 않도록 차단하는 게 좋다. 또는 프로그램의 오류나 외부 환경으로 인해 예외가 발생하는 경우라면 빨리 해당 요청 작업을 취소하고 서버 관리자나 개발자에게 통보해주는 편이낫다. 자바의 환경이 서버로 이동하면서 체크 예외의 활용도와 가치는 점점 떨어지고 있다. 자칫하면 throws Exception으로 점철된 아무런 의미도 없는 메소드들을 낳을 뿐이다. 그래서 대응이 불간으한 체크 예외라면 빨리 런타임 예외로 전환해서 던지는 게 낫다.

자바 초기부터 있었던 JDK의 API와 달리 최근에 등장하는 표준 스펙 또는 오픈소스 프레임워크에서는 API가 발생시키는 예외를 체크 예외 대신 언체크 예외로 정의하는 것이 일반화되고 있다. 예전에는 복구할 가능성이 조금이라도 있다면 체크 예외로 만든다고 생각했는데, 지금은 항상 복구할 수 있는 예외가 아니라면 일단 언체크 예외로 만드는 경향이 있다. 언체크 에외라도 필요하다면 얼마든지 catch 블록으로 잡아서 복구하거나 처리할 수 있다. 하지만 대개는 복구 불가능한 상황이고 보나마나 RuntimeException 등으로 포장해서 던져야 할 테니 아예 API 차원에서 런타임 예외를 던지도록 만든느 것이다.

#### add() 메소드의 예외처리
이전에 나온 add() 메소드는 DuplicatedUserIdException과 SQLException 두 가지의 체크 예외를 던지게 되어 있다. JDBC 코드에서 SQLException이 발생할 수 있는데, 그 원인이 ID 중복이라면 좀 더 의미 이쓴ㄴ 예외인 DuplicatedUserIdException으로 전환해주고, 아니라면 SLQException을 그대로 던지게 했다. DuplicatedUserIdException은 충분히 복구 가능한 예외이므로 add() 메소드를 사용하는 쪽에서 잡아서 대응할 수 있다. 하지만 SQLException은 대부분 복구 불가능한 예외이므로 잡아봤자 처리할 것도 없고, 결국 throws를 타고 계속 앞으로 전달되다가 애플리케이션 밖으로 던져질 것이다. 그럴 바에는 그냥 런타임 예외로 포장해 던져버려서 그 밖의 메소드들이 신경 쓰지 않게 해주는 편이 낫다.

DuplicatedUserIdException도 굳이 체크 예외로 둬야 하는 것은 아니다. DuplicatedUserIdException처럼 의미 있는 예외는 add() 메소드를 바로 호출한 오브젝트 대신 더 앞단의 오브젝트에서 다룰 수 도 있다. 어디에서든 DuplicatedUserIdException을 잡아서 처리할 수 있다면 굳이 체크 예외로 만들지 않고 런타임 예외로 만드는게 낫다. 대신 add() 메소드는 명시적으로 DuplicatedUserIdException을 던진다고 선언해야 한다. 그래야 add() 메소드를 사용하는 코드를 만드는 개발자에게 의미 있는 정보를 전달해줄 수 있다. 러타임 예외도 throws로 선언할 수 있으니 문제 될 것은 없다.

이 방법을 이용해 add() 메소드를 수정해보자. 먼저 사용자 아이닥 중복됐을 때 사용하는 DuplicateUserIdException을 만든다. 필요하다면 언제든 잡아서 처리할 수 있도록 별도의 예외로 정의하기는 하지만, 필요 없다면 신경 쓰지 않아도 되도록 RuntimeException을 상속한 런타임 예외로 ㅁ나든다. 중첩 예외를 만들 수 있도록 생성자를 추가해주는 것을 잊지 말다. 메세지나 예외상황을 전달하는 데 필요한 정보를 더 넣을 수도있다. 아래는 이렇게 만들어진 예외클래스다.

~~~java
// 아이디 중복시 사용하는 예외
public class DuplicateUserIdException extends RuntimeException {
  public DuplicateUserIdException(Throwable cause) {
    super(cause);
  }
}
~~~
이제 add() 메소드를 수정하자. 기존에는 SQLException을 직접 메소드 밖으로 던지게 했는데, 이제는 런타임 예외로 전환해서 던지도록 만든다. 기존의 아이디 중복 때문에 SQLException이 발생한 경우에는 DuplicateUserIdException을 던지게 하는 코드는 그대로 두면 된다.

이제 특별한 의미를 가지는 DuplicateUserIdException 외에 시스템 예외에 해당하는 SQLException은 언체크 예외가 됐다. 따라서 메소드 선언의 throws에 포함시킬 필요가 없다. 반면에 역시 언체크 예외로 만들어지긴 했지만 add() 메소드를 사용하는 쪽에서 아이디 중복 예외를 처리하고 싶은 경우 활용할 수 있음을 알려주도록 DuplicateUserIdException을 메소드의 throws 선언에 포함시킨다.

~~~java
// 예외처리 전략을 적용한 add()
public void add() throws DuplicateUserIdException {
  try {
    // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
    // 그런 기능이 있는 다른 SQLException을 던지는 메소드를 호출하는 코드
  }
  catch(SQLException e) {
    if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
      throw new DuplicateUserIdException(e); //예외 전환
    else
      throw new RuntimeException(e); //예외 포장
  }
}
~~~

이제 이 add() 메소드를 사용하는 오브젝트는 SQLException을 처리하기 위해 불필요한 throws 선언을 할 필요는 없으면서, 필요한 경우 아이디 중복 상황을 처리하기 위해 DuplicatUserIdException을 이용할 수 있다. DuplicateUserIdException이 발생한 경우라면 사용자가 요청한 아이디 대신 사용할 수 있는 추천 아이디를 만들어 아이디 중복 체크 메세지와 함께 제공해주는 방법을 사용하면 좋을 듯하다.

이렇게 런타임 예외를 일반화해서 사용하는 방법은 여러모로 장점이 많다. 단, 런타임 예외로 만들었기 때문에 사용에 더 주의를 기울일 필요도 있다. 컴파일러가 예외처리를 강제하지 않으므로 신경 쓰지 않으면 예외상황을 충분히 고려하지 않은 수도 있기 때문이다. 런타임 예외를 사용하는 경우에는 API 문서나 레퍼런스 문서 등을 통해, 메소드를 사용할 때 발생할 수 있는 예외의 종류와 원인, 활용 방법을 자세히 설명해두자.

#### 애플리케이션 예외
런타임 예외 중심의 전략은 굳이 이름을 붙이자면 낙관적인 예외처리 기법이라고 할 수 있다. 일단 복구할 수 있는 예외는 없다고 가정하고 예외가 생겨도 어차피 런타임 예외이므로 시스템 레벨에서 알아서 처리해줄 것이고, 꼭 필요한 경우는 런타임 예외라도 잡아서 복구하거나 대응해줄 수 있으니 문제 될 것이 없다는 낙과넞ㄱ인 태도를 기반으로하고 있다. 이런 면에서 직접 처리할 수 없는 예외가 대부분이라고 하더라도 혹시 놓치는 예외가 있을 수 있으니, 일단 잡고 보도록 강제하는 체크 예외의 비관적인 접근 방법과 대비된다.
반명에 시스템 또는 외부의 예외상황이 원인이 아니라 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고, 반드시 catch 해서 무엇인가 조치를 취하도록 요구하는 예외도 있다. 이런 예외들을 일반적으로 애플리케이션 예외라고 한다.
예를 들어 사용자가 요청한 금액을 은행계좌에서 출금하는 기능을 가진 메소드가 있다고 생각해보자. 무턱대고 출금을 허용하고, 현재 잔고가 얼마인지 상관없이 요청한 금액만큼 계좌 잔액을 차감하도록 만드는 개발자는 없을 것이다. ㄷ당연히 현재 잔고를 확인하고, 허용하는 범위를 넘어서 출금을 요청하면 축금 작업을 중단시키고, 적절한 경고를 사용자에게 보내야 한다.

이런 기능을 담은 메소드를 설계하는 방법은 두 가지 있다.
첫 번째 방법은 정사적인 출금처리를 했을 경우와 잔고 부족이 발생했을 경우에 각각 다른 종류의 리턴 값을 돌려주는 것이다. 리턴 값을 일종의 결과 상대를 나타내는 정보로 활용한다. 예를 들어 정상적인 출금이 처리된 경우에는 요청금액 자체를 리턴하고, 잔고가 부족한 경우라면 0 또는 -1 같은 특별한 값을 리턴한다. 이 메소드를 호출한 쪽은 반드시 리턴 ㄱ밧을 확인한다. 경우에 따라 작업 흐름이 달라져야 하기 때문이다. 물론 이것은 시스템 오류가 아니므로 기술적으로 보면 두 가지 경우 모두 정상 흐름이다. 하지만 이렇게 리턴 값으로 결과를 확인하고, 예외상황을 체크하면 불편한 점도 있따.

우선 예외상황에 대한 리텀 값을 명확하게 코드화하고 잘 관리하지 않으면 혼란이 생길 수 있다. 정상적인 처리가 안 됐을 때 전달하는 값의 표준 같은 것은 없다. 어떤 개발자는 0을 생각할 수도 있고, -1이나 -999를 돌려주는 개발자도 있다. 일관된 예외상황에서의 결과 값에 대한 정책이 완벽하게 갖춰저 있고, 사전에 상수로 정의해둔 표준 코드를 사용하지 않는다면 자칫 개발자 사이의 의사소통 문제로 인해 제대로 동작하지 않을 위험이 있다. 또 한 가지 문제는 결과 값을 확인하는 조건문이 자주 등장한다는 점이다. 이런 식으로 결과를 돌려주는 메소드를 연이어 사용하는 경우라면 if 블록이 범벅된 코드가 이어질지 모른다. 코드는 지저분해지고 흐름을 파악하고 이해하기가 힘들어질 것이다.

두 번째 방법은 정상적인 흐름을 따르는 코드는 그대로 두고, 잔고 부족과 같은 예외 상황에서는 비즈니스적인 의미를 띤 예외를 던지도록 만드는 것이다. 잔고 부족인 경우라면 InsufficientBalanceException 등을 던진다. 예외상황을 처리하는 catch 블록을 메소드 호출 직후에 둘 필요는 없다. 정상적인 흐름을 따르지만 예외가 발생할 수 있는 코드를 try 블록 안에 깔끔하게 정리해두고 예외상황에 대한 처리는 catch 블록에 모아 둘 수 있기 때문에 코드를 이해하기도 편하다. 번거로운 if 문을 남발하지 않아도 된다.

이때 사용하는 예외는 의도적으로 체크 예외로 만든다. 그래서 개발자가 잊지 않고 잔고 부족처럼 자주 발생 가능한 예외상황에 대한 로직을 구현하도록 강제해주는 게 좋다. 무책임하게 throws Exception을 습관적으로 달아놓은 경우라면 이마저도 놓칠 가능성이 있긴 하지만, 기본적으로 런타임 예외로 만들어두는 것보다는 상대적으로 안전하다.

아래는 예곰을 인출해서 처리한느 코드를 정상 흐름으로 만들어두고, 잔고 부족을 애프리케이션 예외로 만들어 처리하도록 만든 코드다. 애플리케이션 예외인 InsufficientBalanceException을 만들 때는 예외상황에 대한 상세한 정보를 담고 있도록 설계할 필요가 있다. 잔고가 부족한 경우라면 현재 인출 가능한 최대 금액은 얼마인지를 확인해서 예외 정보에 넣어준다면 좋을 것이다.

~~~java
// 애플리케이션 예외를 사용한 코드
try {
  BigDecimal balance = accoutn.withdraw(amount);
  ...
  // 정상적인 처리 결과를 출력하도록 진행
}
catch(InsufficeientBalanceException e) {
  // InsufficientBalanceException에 담긴 인출 가능한 잔고금액 정보를 가져옴
  BigDecimal availFunds = e.getAvaliFunds();
  ...
  // 잔고 부족 안내 메시지를 준비하고 이를 출력하도록 진행
}
~~~

### SQLException은 어떻게 됐나?
지금까지 다룬 예외처리에 대한 내용은 JdbcTemplate을 적용하는 중에 throws SQLException 선언이 왜 사라졌는가를 설명하는 데 필요한 것이었따. 스프링의 예외ㅈ처리 전략과 원칙을 알고 있어야 하기 때문이다. 지금까지 살펴본 예외처리에 관한 내용을 바탕으로, DAO에 존재하는 SQLException에 대해 생각해보자.

먼저 생각해볼 사항은 SQLException은 과연 복구가 가능한 예외인가이다. 99%의 SQLException은 코드 레벨에서는 복구할 방법이 없다. 프로그램의 오류 또는 개발자의 부주의 때문에 발생하는 경우이거나, 통제할 수 없는 외부상황 때문에 발생하는 것이다. 예를 들어 SQL 문법이 틀렸거나, 제약조건을 위반했거나, DB 서버가 다운됐다거나, 네트워크가 불안정하거나, DB 커넥션 풀이 꽉 차서 DB 커넥션을 가져올 수 없는 경우 등이다.

시스템의 예외라면 당연히 애플리케이션 레벨에서 복구할 방법이 없다. 관리자나 개발자에게 빨리 예외가 발생했다는 사실이 알려지도록 전달하는 방법밖에는 없다. 마찬가지로 애플리케이션 코드의 버그나 미처 다루지 않았떤 범위를 벗어난 값 때문에 발생한 예외도 역시 복구할 방법이 없다. INSERT 문에 넣을 파라미터 값을 미리 체크하지 않아서 발생하는 SQLException을 어떻게 복구할 것인가? 입력 단계에서 검증을 강화앵야 한다는 사실을 개발자가 빨리 인식할 수 있도록 발생한 예외를 빨리전달하는 것 외에는 할 수 있는게 없다.

앞에서 잠깐 살펴본 ID 중복 문제를 시행착오 기법으로 확인하는 조금 무식한 접근방법 정도라면 모를까, 대부분의 SQLException은 복구가 불가능하다. 더군다나 DAO 밖에서 SQLException을 다룰 수 있는 간으성은 거의 없다. 따라서 예외처리 전략을 적용해야 한다. 필요도 없는 기계적인 throws 선언이 등장하도록 방치하지 암ㅎ고 간으한한 빨리 언체크/런타임 예외로 전환해줘야 한다.

스프링의 JdbcTemplate은 바로 이예외처리 전략을 따르고 있다. JdbcTemplate 템플릿과 콜백 안에서 발생하는 모든 SQLException을 런타임 예외인 DataAccessException으로 포장해서 던져준다. 따라서 JdbcTemplate을 사용하는 UserDao 메소드에선 꼭 필요한 경우에만 런타임 예외인 DataAccessException을 잡아서 처리하면 되고 그 외의 경우에는 무시해도 된다. 그래서 DAO 메소드에서 SQLException이 모두 사라진 것이다.

JdbcTemplate의 update(), queryForInt(), query() 메소드 선언을 잘 살펴보면 다음과 같인 모두 throws DataAccessException이라고 되어 있음을 발견할 수 있다. throws로 선언되어 있긴 하지만 DataAccessException이 런타임 예외이므로 update()를 사용하는 메소드에서 이를 잡거나 다시 던질 의무는 없다.
~~~java
public intupdate(final String sql) throws DataAccessException { ... }
~~~

그 밖에도 스프링의 API 메소드에 정의되어 있는 대부분의 예외는 런타임 예외다. 따라서 발생 가능한 예외가 있다고 하더라도 이를 처리하도록 강제하지 않는다.
